### ISSUE TITLE
"stack": "TypeError: Cannot read properties of undefined (reading 'join')

### ISSUE THREAD

**Issue by 1day0** [HurricanoBot/Hurricano#47]
Hello, I have a problem with the open source code an error is displayed and since I'm using the nodeJS I'm a little lost I send you the error below: 

"stack": "TypeError: Cannot read properties of undefined (reading 'join')

at generateHelpEmbed (C:\Users\\IRdark\Desktop\Hurricano-main\Hurricano-main\bot\commands\information\help.js:201:50)

    at Command.run (C:\Us\ers\\IRdark\Desktop\Hurricano-main\Hurricano-main\bot\commands\information\help.js:237:21)

    at MessageEvent.run (C:\Us\ers\\IRdark\\Desktop\Hurricano-main\Hurricano-main\bot\events\information\message.js:433:21)

    at processTicksAndRejections (node:internal/process/task_queues:96:5)"

Here's the error ^^"

**Comment by 1day0** [comment]
I can't do help orders or anything else either

**Comment by 1day0** [comment]
and the help command with mention or prefix dont work in the chat pls help me pls ^^

**Comment by 1day0** [comment]
when I mention the bot it tells me that its prefix is "hr!" while in config.json I put "&" is this normal?

**Comment by DragonZV** [comment]
hi, the giveaway module of Hurricano doesn't work as of now.

**Comment by DragonZV** [comment]
> when I mention the bot it tells me that its prefix is "hr!" while in config.json I put "&" is this normal?

did you try resetting the database?

**Comment by 1day0** [comment]
> > quand je mentionne le bot, il me dit que son préfixe est "hr!" alors que dans config.json j'ai mis "&" est-ce normal ?
> 
> as-tu essayé de réinitialiser la base de données ?

No can you tell me how to do it plss

**Comment by 1day0** [comment]
> salut, le module cadeau d'Hurricano ne fonctionne pas pour le moment.

No problem, I'll wait with pleasure ^^

( again sorry for the inconvenience I'm a basic python developer ^^" )

**Comment by DragonZV** [comment]
> > > quand je mentionne le bot, il me dit que son préfixe est "hr!" alors que dans config.json j'ai mis "&" est-ce normal ?
> > 
> > 
> > as-tu essayé de réinitialiser la base de données ?
> 
> No can you tell me how to do it plss

use mongodb compass

**Comment by 1day0** [comment]
mongodb compass ???

**Comment by DragonZV** [comment]
yes
